name: platform-flywheel
type: service
minMemory: 1024
maxMemory: 4096
cpu: 512
segment: internal
ports:
  - 8080
  - 9090:9090
ulimits:
  nofile:
    soft: 500000
    hard: 500000
environment:
healthCheck:
  endpoint: /health
  timeoutSeconds: 1
  intervalSeconds: 30
