name: platform-flywheel
type: service
minMemory: 1280
maxMemory: 2048
cpu: 1024
segment: internal
tcpPorts:
  - 8080
environment:
healthCheck:
  endpoint: /health
  timeoutSeconds: 1
  intervalSeconds: 30
