name: platform-flywheel
type: service
minMemory: 1024
maxMemory: 4096
cpu: 1024
segment: internal
tcpPorts:
  - 8080
environment:
healthCheck:
  endpoint: /health
  timeoutSeconds: 1
  intervalSeconds: 30
